---
- hosts: all
  become: yes
  tasks:


#########################################
# FEDORA
#    - apt: name=python-virtualenv
#    - apt: name=python-pip
    - apt:
        name: "{{ item }}"
      with_items:
        - python-mysqldb
        - mysql-client

    - debug: var=mysql_login_host
    - debug: var=mysql_local_installation
    - name: Ensure fcrepo database exists.
      mysql_db:
        login_host: "{{ mysql_login_host }}"
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_login_password }}"
        state: present
        name: fedora3

    - name: Ensure fcrepo user exists.
      mysql_user:
        login_host: "{{ mysql_login_host }}"
        login_user: "{{ mysql_login_user }}"
        login_password: "{{ mysql_login_password }}"
        state: present
        name: fedoraAdmin
        password: fedoraAdmin
        priv: fedora3.*:ALL
