---
- name: Check if Solr sources have been downloaded already
  stat: path="{{ work_dir }}/solr-{{solr_version}}"
  register: solr

- name: Get Solr
  unarchive:
    copy: no
    dest: "{{ work_dir }}/"
    src: "http://archive.apache.org/dist/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz"
#    src: "http://archive.apache.org/dist/lucene/solr//solr-{{solr_version}}.tgz"
    owner: tomcat7
    group: tomcat7
  when: solr.stat.exists == False

- name: Ensure that tomcat7 owns Solr
  file:
    state: directory
    path:  "{{ work_dir }}/solr-{{solr_version}}"
    owner: tomcat7
    group: tomcat7
    recurse: yes

- name: Link Solr
  file: 
    dest: "{{ solr_home }}"
    src: "{{ work_dir }}/solr-{{solr_version}}/example/solr"
    state: link
    owner: tomcat7
    group: tomcat7

- name: copy solr.war into tomcat
  copy: 
    dest: "/var/lib/tomcat7/webapps/solr.war"
    src: "{{ work_dir }}/solr-{{solr_version}}/dist/solr-{{solr_version}}.war"
    owner: tomcat7
    group: tomcat7
    remote_src: yes

- name: link solr to tomcat
  file: 
    src: "{{solr_home}}" 
    dest: /var/lib/tomcat7/solr
    state: link
    owner: tomcat7
    group: tomcat7

- name: Restart tomcat
  service:
    name: tomcat7
    state: restarted
